baseurl:        "https://support.growthbeat.com/"
title:          "Growthbeatドキュメント |"
contentdir:     "content"
publishdir:     "public"
layoutdir:      "layouts"
staticdir:      "static"
uglyUrls:       false
metaDataFormat: "yaml"

blackfriday:
  plainIDAnchors: true

Params:
  # Date Format
  DateForm:      "Mon, Jan 2, 2006"
