#!/bin/bash

readonly LOCATION=`pwd`

function usage() {
cat<<_EOT_
Usage:
  $0 <title>.md

Description:
  Create a new post

_EOT_
exit 1
}

if  [ -z "$1" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
  usage
fi

echo -e "\033[0;32mCreate a new post which file name is ${1}\033[0m"

hugo new "$1" --config="${LOCATION}/config.yml"
