#!/bin/bash

readonly LOCATION=`pwd`

function usage() {
cat<<_EOT_
Usage:
  $0 <language>

Description:
  Start server specific language

_EOT_
exit 1
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
  usage
fi

echo -e "\033[0;32mStart server\033[0m"
hugo server --buildDrafts --watch --verbose --source=${LOCATION} --config="${LOCATION}/config_ja.yml"
